# Generated by Django 4.2.3 on 2023-07-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # # migrations.CreateModel(
        # #     name="Cutter",
        # #     fields=[
        # #         ("id", models.AutoField(primary_key=True, serialize=False)),
        # #         ("name", models.CharField(max_length=128, unique=True)),
        # #         ("supplier", models.CharField(max_length=128, null=True)),
        # #         ("minHoleTole", models.CharField(max_length=128, null=True)),
        # #         ("maxHoleTole", models.CharField(max_length=128, null=True)),
        # #         ("minDia", models.CharField(max_length=128, null=True)),
        # #         ("maxDia", models.CharField(max_length=128, null=True)),
        # #         ("minDepDia", models.CharField(max_length=128, null=True)),
        # #         ("maxDepDia", models.CharField(max_length=128, null=True)),
        # #         ("capMat", models.TextField(null=True)),
        # #         ("cutterMat", models.CharField(max_length=128, null=True)),
        # #         ("capPro", models.TextField(null=True)),
        # #         ("cutterCost", models.CharField(max_length=128, null=True)),
        # #         ("cutterImg", models.FileField(null=True, upload_to="")),
        # #         ("cutterRemark", models.TextField(null=True)),
        # #     ],
        # # ),
        # # migrations.CreateModel(
        # #     name="Feature",
        # #     fields=[
        # #         ("id", models.AutoField(primary_key=True, serialize=False)),
        # #         ("classFirst", models.CharField(max_length=128)),
        # #         ("classSecond", models.CharField(max_length=128, null=True)),
        # #         ("classID", models.CharField(max_length=128, null=True)),
        # #         ("classDes", models.TextField(null=True)),
        # #         ("paraDef", models.TextField(null=True)),
        # #         ("imgPath", models.FileField(null=True, upload_to="")),
        # #         ("remark", models.TextField(null=True)),
        # #     ],
        # # ),
        # migrations.CreateModel(
        #     name="Fixture",
        #     fields=[
        #         ("id", models.AutoField(primary_key=True, serialize=False)),
        #         ("name", models.CharField(max_length=128, unique=True)),
        #         ("fixtureType", models.CharField(max_length=128, null=True)),
        #         ("fixtureName", models.CharField(max_length=128, null=True)),
        #         ("fixtureCode", models.CharField(max_length=128, null=True)),
        #         ("geoDim", models.CharField(max_length=128, null=True)),
        #         ("partType", models.CharField(max_length=128, null=True)),
        #         ("partStruct", models.CharField(max_length=128, null=True)),
        #         ("partMat", models.CharField(max_length=128, null=True)),
        #         ("partSize", models.CharField(max_length=128)),
        #         ("InterfaceDim", models.TextField(null=True)),
        #         ("fixtureImg", models.FileField(null=True, upload_to="")),
        #         ("fixtureRemark", models.TextField(null=True)),
        #         ("otherFields", models.TextField(null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="Head",
        #     fields=[
        #         ("id", models.AutoField(primary_key=True, serialize=False)),
        #         ("name", models.CharField(max_length=128, null=True, unique=True)),
        #         ("headType", models.CharField(max_length=128, null=True)),
        #         ("headStruct", models.CharField(max_length=128, null=True)),
        #         ("headDepth", models.CharField(max_length=128, null=True)),
        #         ("toolDiamRange_max", models.CharField(max_length=128, null=True)),
        #         ("toolDiamRange_min", models.CharField(max_length=128, null=True)),
        #         ("appMach", models.CharField(max_length=128, null=True)),
        #         ("headImg", models.FileField(null=True, upload_to="")),
        #         ("headRemark", models.TextField(null=True)),
        #         ("otherFields", models.TextField(null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="Mach",
        #     fields=[
        #         ("id", models.AutoField(primary_key=True, serialize=False)),
        #         ("name", models.CharField(max_length=128, null=True, unique=True)),
        #         ("machType", models.CharField(max_length=128, null=True)),
        #         ("travelX", models.CharField(max_length=128, null=True)),
        #         ("travelY", models.CharField(max_length=128, null=True)),
        #         ("travelZ", models.CharField(max_length=128, null=True)),
        #         ("travelA", models.CharField(max_length=128, null=True)),
        #         ("travelB", models.CharField(max_length=128, null=True)),
        #         ("travelC", models.CharField(max_length=128, null=True)),
        #         ("PrecisionX", models.CharField(max_length=128, null=True)),
        #         ("PrecisionY", models.CharField(max_length=128, null=True)),
        #         ("PrecisionZ", models.CharField(max_length=128, null=True)),
        #         ("PrecisionA", models.CharField(max_length=128, null=True)),
        #         ("PrecisionB", models.CharField(max_length=128, null=True)),
        #         ("PrecisionC", models.CharField(max_length=128, null=True)),
        #         ("worktableSize_length", models.CharField(max_length=128, null=True)),
        #         ("worktableSize_width", models.CharField(max_length=128, null=True)),
        #         ("load", models.CharField(max_length=128, null=True)),
        #         ("process", models.CharField(max_length=128, null=True)),
        #         ("feature", models.CharField(max_length=128, null=True)),
        #         ("headID", models.CharField(max_length=128, null=True)),
        #         ("machImg", models.FileField(null=True, upload_to="")),
        #         ("machRemark", models.TextField(null=True)),
        #         ("otherFields", models.TextField(null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="ManuCapRule",
        #     fields=[
        #         ("id", models.AutoField(primary_key=True, serialize=False)),
        #         ("name", models.CharField(max_length=128, null=True, unique=True)),
        #         ("captype", models.CharField(max_length=128, null=True)),
        #         ("manuType", models.CharField(max_length=128, null=True)),
        #         ("featType1", models.CharField(max_length=128, null=True)),
        #         ("featType2", models.CharField(max_length=128, null=True)),
        #         ("featPro", models.CharField(max_length=128, null=True)),
        #         ("resType", models.CharField(max_length=128, null=True)),
        #         ("content", models.TextField(null=True)),
        #         ("script", models.TextField(null=True)),
        #         ("inputParaList", models.TextField(null=True)),
        #         ("outputParaList", models.TextField(null=True)),
        #         ("paraTable", models.CharField(max_length=128, null=True)),
        #         ("ManuCapRemark", models.TextField(null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="Publisher",
        #     fields=[
        #         ("id", models.AutoField(primary_key=True, serialize=False)),
        #         ("name", models.CharField(max_length=64)),
        #         ("addr", models.CharField(max_length=128)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="Rule",
        #     fields=[
        #         ("id", models.AutoField(primary_key=True, serialize=False)),
        #         ("name", models.CharField(max_length=128, null=True, unique=True)),
        #         ("ruleTypeFirst", models.CharField(max_length=128, null=True)),
        #         ("ruleTypeSecond", models.CharField(max_length=128, null=True)),
        #         ("manuType", models.CharField(max_length=128, null=True)),
        #         ("featTypeFirst", models.CharField(max_length=128, null=True)),
        #         ("featTypeSecond", models.CharField(max_length=128, null=True)),
        #         ("featPro", models.CharField(max_length=128, null=True)),
        #         ("content", models.TextField(null=True)),
        #         ("imgPath", models.TextField(null=True)),
        #         ("script", models.TextField(null=True)),
        #         ("remark", models.TextField(null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="TableFunction",
        #     fields=[
        #         ("id", models.AutoField(primary_key=True, serialize=False)),
        #         ("name", models.CharField(max_length=128, unique=True)),
        #         (
        #             "functionName",
        #             models.CharField(max_length=128, null=True, unique=True),
        #         ),
        #         ("inputPara", models.TextField(null=True)),
        #         ("outputPara", models.TextField(null=True)),
        #         ("sql", models.TextField(null=True)),
        #         ("remark", models.TextField(null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="KnowledgeParaTable",
        #     fields=[
        #         ("id", models.AutoField(primary_key=True, serialize=False)),
        #         ("name", models.CharField(max_length=128)),
        #         ("paraType", models.CharField(max_length=128, null=True)),
        #         ("defaultValue", models.TextField(null=True)),
        #         ("remark", models.TextField(null=True)),
        #         (
        #             "ruleid",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 to="app01.manucaprule",
        #             ),
        #         ),
        #         (
        #             "tableFunction",
        #             models.ForeignKey(
        #                 null=True,
        #                 on_delete=django.db.models.deletion.SET_NULL,
        #                 to="app01.tablefunction",
        #                 to_field="name",
        #             ),
        #         ),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="Book",
        #     fields=[
        #         ("id", models.AutoField(primary_key=True, serialize=False)),
        #         ("title", models.CharField(max_length=64, unique=True)),
        #         (
        #             "publisher",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 to="app01.publisher",
        #             ),
        #         ),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="Author",
        #     fields=[
        #         ("id", models.AutoField(primary_key=True, serialize=False)),
        #         ("name", models.CharField(max_length=16, unique=True)),
        #         ("book", models.ManyToManyField(to="app01.book")),
        #     ],
        # ),
    ]
