# Generated by Django 4.1.4 on 2023-07-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('fixtureType', models.CharField(max_length=128, null=True)),
                ('fixtureName', models.CharField(max_length=128, null=True)),
                ('fixtureCode', models.CharField(max_length=128, null=True)),
                ('geoDim', models.CharField(max_length=128, null=True)),
                ('partType', models.CharField(max_length=128, null=True)),
                ('partStruct', models.CharField(max_length=128, null=True)),
                ('partMat', models.CharField(max_length=128, null=True)),
                ('partSize', models.CharField(max_length=128)),
                ('InterfaceDim', models.TextField(null=True)),
                ('fixtureImg', models.FileField(null=True, upload_to='')),
                ('fixtureRemark', models.TextField(null=True)),
                ('otherFields', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cutter',
            name='cutterImg',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
