# Generated by Django 4.1.4 on 2023-07-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_fixture_alter_cutter_cutterimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('machType', models.CharField(max_length=128, null=True)),
                ('travelX', models.CharField(max_length=128, null=True)),
                ('travelY', models.CharField(max_length=128, null=True)),
                ('travelZ', models.CharField(max_length=128, null=True)),
                ('travelA', models.CharField(max_length=128, null=True)),
                ('travelB', models.CharField(max_length=128, null=True)),
                ('travelC', models.CharField(max_length=128, null=True)),
                ('PrecisionX', models.CharField(max_length=128, null=True)),
                ('PrecisionY', models.CharField(max_length=128, null=True)),
                ('PrecisionZ', models.CharField(max_length=128, null=True)),
                ('PrecisionA', models.CharField(max_length=128, null=True)),
                ('PrecisionB', models.CharField(max_length=128, null=True)),
                ('PrecisionC', models.CharField(max_length=128, null=True)),
                ('worktableSize_length', models.CharField(max_length=128, null=True)),
                ('worktableSize_width', models.CharField(max_length=128, null=True)),
                ('load', models.CharField(max_length=128, null=True)),
                ('process', models.CharField(max_length=128, null=True)),
                ('feature', models.CharField(max_length=128, null=True)),
                ('headID', models.CharField(max_length=128, null=True)),
                ('machImg', models.FileField(null=True, upload_to='')),
                ('machRemark', models.TextField(null=True)),
                ('otherFields', models.TextField(null=True)),
            ],
        ),
    ]
