# Generated by Django 4.1.4 on 2023-07-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_mach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('headType', models.CharField(max_length=128, unique=True)),
                ('headStruct', models.CharField(max_length=128, unique=True)),
                ('headDepth', models.CharField(max_length=128, unique=True)),
                ('toolDiamRange_max', models.CharField(max_length=128, unique=True)),
                ('toolDiamRange_min', models.CharField(max_length=128, unique=True)),
                ('appMach', models.CharField(max_length=128, unique=True)),
                ('headImg', models.FileField(null=True, upload_to='')),
                ('headRemark', models.TextField(null=True)),
                ('otherFields', models.TextField(null=True)),
            ],
        ),
    ]
