# Generated by Django 4.1.4 on 2023-07-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='appMach',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='headDepth',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='headStruct',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='headType',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='toolDiamRange_max',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='toolDiamRange_min',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mach',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
